version: '3'
services:
  web:
    build: '.'
    image: octopushead/ascend-user:latest
    environment:
      - MONGO_URI=${MONGO_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHANEL_SECRET=${CHANEL_SECRET}
      - CHANEL_ACCESS_TOKEN=${CHANEL_ACCESS_TOKEN}
    volumes:
      - /home/root/certs:/certs:ro
    ports:
      - 5000:5000


