version: '3'
services:
  web:
    build: '.'
    image: octopushead/ascend-user:latest
    environment:
      - MONGO_URI=${MONGO_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - 5000:5000

